# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example

	pod 'MBProgressHUD', '~> 1.2.0'
  pod 'SHPopView', '~> 1.1.0'
  pod 'SHExtension/UIView', '~> 1.5.5'
  pod 'SHExtension/UIButton', '~> 1.5.5'


end
